Projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('modelos/', include('modelos.urls')),
    path('perfil/', include('perfil.urls')),
    path('usuario/', include('usuario.urls')), 
    path('clientes/', include('clientes.urls')),   
    path('serviços/', include('serviços.urls'))
]

clientes/urls.py
from unicodedata import name    
from django.urls import URLPattern, path
from . import views

urlpatterns = [
    path('', views.listar, name='listar'),
    path('<int:id>', views.clientes, name="clientes"),
    path('editar/<int:id>', views.editar, name="editar"),
    path('excluir/<int:id>', views.excluir, name="excluir"),
]

home/urls.py
from unicodedata import name    
from django.urls import URLPattern, path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('gerador', views.gerador, name='gerador'),
        path('baixar', views.baixar, name="baixar")
]

clientes/models.py
from django.db import models
from django.contrib.auth.models import User
from serviços.models import serviço
from django.contrib.auth import get_user_model

class Cliente(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    tel = models.CharField(max_length=19)
    pagamento = models.CharField(max_length=19, blank=True)
    Serviço = models.ForeignKey(serviço, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.PROTECT)


clientes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Cliente


class CriarCliente(ModelForm):
    class Meta:
        model = Cliente
        fields = ('nome', 'pagamento', 'tel', 'Serviço')
        labels = {'nome':'Nome', 'pagamento':'Último pagamento', 'tel':'Telefone'}

class EditarCliente(ModelForm):
    class Meta:
        model = Cliente
        fields = ('nome', 'pagamento', 'tel')
        labels = {'nome':'Nome', 'pagamento':'Último pagamento', 'tel':'Telefone'}

clientes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . forms import CriarCliente, EditarCliente
from .models import Cliente
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from serviços.models import serviço
from django.urls import reverse

@login_required
def listar(request):
    cts = Cliente.objects.all()
    context = {
        'cts': cts, 
    }

    return render(request, 'clientes/listar.html', context)

@login_required
def clientes(request, id):
    servico = serviço.objects.get(pk=id)
    cts = Cliente.objects.filter(Serviço=servico)

    if request.method == 'POST':
        form = CriarCliente(request.POST)
        form.instance.user = request.user
        
        if form.is_valid():
            form.save()
            return redirect(reverse('clientes', args=[id]))
            

    else:
            form = CriarCliente

    context = {
        'form': form,
        'cts': cts, 
        'servico' : servico
        }


    return render(request, 'clientes/clientes.html', context)
   


@login_required()
def editar(request, id):
    cliente = get_object_or_404(Cliente, pk=id)
    s = cliente.Serviço.id
    form = EditarCliente(instance=cliente)

    if request.method == 'POST':
        form = EditarCliente(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect(reverse('clientes', args=[s]))
    
    context = {'form': form, 'cliente': cliente}

    return render(request, 'clientes/mult.html', context)

def excluir(request, id):
    cliente = get_object_or_404(Cliente, pk=id)
    s = cliente.Serviço.id
    cliente.delete()
    return redirect(reverse('clientes', args=[s]))


templates/clientes/clientes.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="card">
    <div class="card-body">
      
         

<!-- Botão para acionar modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ExemploModalCentralizado">
    Adicionar Cliente
  </button>

  <a href="/serviços/"><button class="btn btn-secondary">Voltar</button></a>
<form action="." method="post">

  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Adicione aqui novos serviços</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Salvar">
        </form>
        </div>

      </div>
    </div>
  </div>
  <div class="modal fade" id="ExemploModalCentralizado" tabindex="-1" role="dialog" aria-labelledby="TituloModalCentralizado" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="TituloModalCentralizado">Adione aqui novos clientes</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          
          <form method="POST">
            {% csrf_token %}
            <p>
    <label for="id_nome">Nome:</label>
    <input type="text" name="nome" maxlength="100" required id="id_nome">
    
    
  </p>

  
  <p>
    <label for="id_pagamento">Último pagamento:</label>
    <input type="text" name="pagamento" maxlength="19" id="id_pagamento">
    
    
  </p>

  
  <p>
    <label for="id_tel">Telefone:</label>
    <input type="text" name="tel" maxlength="19" required id="id_tel">
    
    
  </p>

  
  <p hidden>
    <label for="id_Serviço">Serviço:</label>
    <select name="Serviço" required id="id_Serviço">
  <option value="{{servico.id}}" selected>---------</option>

</select>
    
    
      
    
  </p>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                 <input type="submit" value="Salvar">
              </div>
          </form>
            


           
    
        </div>
      </div>
    </div>
  </div>
 </form>

 

        <br><br>


        <table class="table table-bordered">
            <thead>
              <tr>
              
                <th scope="col">Nome</th>
                <th scope="col">Telefone</th>
                <th scope="col">Data último pagamento</th>
                <th class = "text-center">Ações</th>
              </tr>
            </thead>

            <tbody>

              {% for Cliente in cts %}

              <tr>
              
                <td>{{Cliente.nome}}</td>
                <td>{{Cliente.tel}}</td>
                <td>{{Cliente.pagamento}}</td>
                
                <td class = "text-center">
                    
                    <a class="btn btn-warning" href="editar/{{Cliente.id}}">Editar</a>
               
                    <a class="btn btn-danger" href="excluir/{{Cliente.id}}">Excluir</a>

                </td>
                
              </tr>
              {% endfor %}
            </tbody>
          </table>

    </div>
</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% endblock %}

templates/clientes/listar.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="card">
    <div class="card-body">
        <br><br>

      <table class="table table-bordered">
            <thead>
              <tr>
              
                <th scope="col">Nome</th>
                <th scope="col">Telefone</th>
                <th scope="col">Data último pagamento</th>
                <th class = "text-center">Ações</th>
              </tr>
            </thead>

            <tbody>

              {% for Cliente in cts %}

              <tr>
              
                <td>{{Cliente.nome}}</td>
                <td>{{Cliente.tel}}</td>
                <td>{{Cliente.pagamento}}</td>
                
                <td class = "text-center">
                    
                    <a class="btn btn-warning" href="editar/{{Cliente.id}}">Editar</a>
               
                    <a class="btn btn-danger" href="excluir/{{Cliente.id}}">Excluir</a>

                </td>
                
              </tr>
              {% endfor %}
            </tbody>
          </table>

    </div>
</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% endblock %}

templates/clientes/mult.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="card">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <br>
            <button class="btn btn-success" type="submit">Salvar</button>
            <a href="/clientes/" class="btn btn-danger">Cancelar</a>

        </form>
    </div>
</div>

{% endblock %}